### ISSUE TITLE
Purpose of the interpreter

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.Compiler.PortaCode#4]
Im curious on the purpose of the interpreter?

**Comment by dsyme** [comment]
It's used in fabulous

**Comment by 7sharp9** [comment]
Thanks for the detailed information.

**Comment by dsyme** [comment]
More specifically: it's used for the "LiveUpdate" feature of Fabulous, to interpret the Elmish model/view/update application code on-device.

It's not actually necessary on Android since full mono JIT is available. On iOS it appears necessary.

The interpreter may also be useful for other live checking tools, because you get escape the whole complication of actual IL generation, Reflection emit and reflection invoke, and no actual classes et.c are generated.  We can also adapt the interpreter over time to do things like report extra information back to the host.  

The input code format (PortaCode) is derived from FSharp.Compiler.Service expressions, the code is in this repo.  The semantics of interpretation can differ from the semantics of .NET F# code.  Perf is not good but in many live check scenarios you're sitting on a base set of DLLs which are regular .NET code and are efficiently invoked.

**Comment by dsyme** [comment]
Added comment to README.md
